### ISSUE TITLE
Envy's Knife doesn't copy Digigrade Legs

### ISSUE THREAD

**Issue by Owai-Seek** [citadel-station/citadel-main#9345] opened 2019-09-23 01:50 UTC
Issue reported from  Round ID: 19303 (Citadel Station 13)

Reporting client version: 512

What it says on the tin, Envy's knife doesn't copy digigrade legs now.

**Comment by Weblure** [comment] 2019-10-02 21:20
Probably just needs a var name change somewhere in the code, after the leg update was merged. Who was the creator of that PR?

**Comment by Weblure** [comment] 2019-10-02 21:24
Found em
@Poojawa Can you confirm if this is caused by #9277 ?

**Comment by Poojawa** [comment] 2019-10-03 18:54
It does and it doesn't. 

Envy's knife doesn't actually transform persay because it's more of just copy/paste, rather than forcefully checking on_species_gain

**Closed as completed** 2019-10-25 02:15 UTC
