### ISSUE TITLE
Laughter/Slaughter demons bleed when hit by bullets.

### ISSUE THREAD

**Issue by GrayRachnid** [citadel-station/citadel-main#10175] opened 2019-12-13 19:54 UTC
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
>Clean an area and entrap a demon
>Buckshot
>He bleeds
>He leaves

**Comment by GrayRachnid** [comment] 2019-12-13 19:54
#10124 probably related

**Comment by Putnam3145** [comment] 2019-12-13 20:18
probably a duplicate of #10149

**Comment by Ghommie** [comment] 2019-12-20 09:00
Should have been fixed by now since that bloodsuckers are in.
Feel free to open another issue in case I'm wrong.

**Closed as completed by Ghommie** 2019-12-20 09:00 UTC
