### ISSUE TITLE
Transcendent Olfaction just doesn't work.

### ISSUE THREAD

**Issue by Zellular** [citadel-station/citadel-main#11258] opened 2020-02-26 22:57 UTC
## Testmerges:
#10327 

## Reproduction:
Gain the Transcendent Olfaction mutation, try to smell an Item, yours or otherwise. It doesn't seem to register you holding an item, and doesn't save it for you to track later, using it with an empty hand later will just give you the message that you've not smelled anything or aren't holding anything.

**Comment by Ludox235** [comment] 2020-04-05 01:58
Worked fine for me

**Comment by DeltaFire15** [comment] 2020-05-18 15:36
I can't seem to reproduce this, Transcendent Olfaction appears to work fine for me including the criteria on when an item actually inherits a smell (touching it without gloves usually)
Maybe you were using an item that did have no smell because it was only handled with gloves?
(Or maybe it was just fixed in the meantime)

**Closed as completed** 2020-12-24 21:20 UTC
Labels: Bug
