### ISSUE TITLE
Safety Fire™

### ISSUE THREAD

**Issue by LSommers** [citadel-station/citadel-main#190] opened 2017-02-02 17:46 UTC
Players, when they catch fire, don't take damage from said fire, nor do their clothes. Full-tile (IE Plasmafire) causes burn damage, but being caught on fire does not. Bonfires and Dragonsbreath Rounds both cause Safety Fire™. You can sleep on a bonfire without you or your clothes taking damage, but it still damages items as intended. Likewise, Dragonsbreath rounds only cause brute and bleed damage.

**Comment by Poojawa** [comment] 2017-02-03 05:37
Unable to reproduce. It may have been a controller/lag issue making the handle_fire proc to not be called

**Comment by Poojawa** [comment] 2017-02-03 06:16
Yeah, barring a MC bug, this is more or less fixed with #189

**Closed as completed by Poojawa** 2017-02-03 06:16 UTC
Labels: Bug
