### ISSUE TITLE
AI initiating Doomsday while dead

### ISSUE THREAD

**Issue by InquisitiveEpidemic** [citadel-station/citadel-main#10669] opened 2020-01-23 05:41 UTC
Issue reported from  Round ID: 21106 (Citadel Station 13)

Reporting client version: 512

The AI killed during the round, a MALF AI during a traitor round, initiated the AI doomsday after reentering it's dead body.

**Comment by Ghommie** [comment] 2020-01-23 14:35
duplicate of #10666.

**Closed as completed by Ghommie** 2020-01-23 14:35 UTC
