### ISSUE TITLE
Rechargable and "Infinite" welders can just be completely emptied and made to never recharge again.

### ISSUE THREAD

**Issue by TheObserver-sys** [citadel-station/citadel-main#13700] opened 2020-11-23 10:10 UTC
## Round ID: 
25120, playing as an ashlander.

## Reproduction:
STEP 1: Make Sandstone Furnace
STEP 2: Dump your complimentary Experimental/Brass/Alien Welder into the forge
STEP 3: Try not to cry as your welder never refills
STEP 4: Cry a lot

**Comment by TheObserver-sys** [comment] 2020-11-23 10:12
If I had to guess, it's a big funny caused by https://github.com/Citadel-Station-13/Citadel-Station-13/pull/13604

**Comment by lolman360** [comment] 2020-11-23 11:18
do they not regenerate fuel anymore
agony

**Comment by DeltaFire15** [comment] 2020-11-23 16:02
The bug is not caused by the PR, but not fixed by it either.
Welders only start processing the first time they are switched on, and process() handles fuel regen, both in the old and new versions.
(Even 'better', they exclusively regen fuel while on, because having them off stops processing)

**Comment by TheObserver-sys** [comment] 2020-11-23 19:01
Thing is, I remember the old ones still recharging if you dumped it into the furnace, as it helped me do my ashen forge gimmick.

**Closed as completed** 2020-12-25 17:28 UTC
Labels: Bug
