### ISSUE TITLE
vampire combat mode movement locked up

### ISSUE THREAD

**Issue by InquisitiveEpidemic** [citadel-station/citadel-main#11445] opened 2020-03-12 03:05 UTC
Issue reported from  Round ID: 21999 (Citadel Station 13)

Reporting client version: 513

Round ID 21999
As chaplain I was mesmerized by Reagen Sables a vampire, cable cuffed, buckled to a Persuasion Rack attempted but failed to resist out of it and thralled to Reagen Sables after being beaten with a service radio headset. After that I was unable to move whatsoever or use my hands and reconnecting and restarting did nothing to return controls. I am told it is the combatmode_locked bug by Putnam.
I ahelped and after 20-30 minutes of troubleshooting no solution was found and was told to relay the following
Putnam: Yes, go over precisely what happened up to and after the thralling, round ID is 21999, also mention that i
1. called update_stat
2. removed a combat mode lock trait with a null value associated with it
3. called SetAllImmobility(0,0) on you
4. ahealed you

**Comment by necromanceranne** [comment] 2020-03-14 09:35
@kevinz000 was this ever fixed?

**Comment by Arturlang** [comment] 2020-03-17 22:43
Very wierd, its really hard to fix this if you cant reproduce it. Also, is this a mobility flags bug or bloodsucker, cant say.

**Comment by Ghommie** [comment] 2020-04-10 13:42
Should be fixed in #11785.

**Closed as completed by Ghommie** 2020-04-10 13:42 UTC
