### ISSUE TITLE
Citadel Main - Cargo delivery is broken

### ISSUE THREAD

**Issue by DeezNyas** [citadel-station/citadel-main#8572] opened 2019-06-08 08:59 UTC
Tldr; Regardless of what's put on the destination tagger, what tile it's on, what station it is, any other combination of things, it always sends things straight to disposals. could have something to do with tagger ID being broken, no clue. love u

**Comment by Poojawa** [comment] 2019-06-09 06:39
![](https://i.gyazo.com/a4845bf391fafd2a0af002efd70711d5.png)

can't reproduce. Please ensure you're correctly packaging objects before tagging them.

**Comment by CdrCross** [comment] 2019-07-23 18:25
The broken cargo deliveries have long since been fixed. Please close this issue.

**Closed as completed** 2019-11-10 18:29 UTC
