### ISSUE TITLE
Shuttles not moving

### ISSUE THREAD

**Issue by SandPoot** [citadel-station/citadel-main#9845] opened 2019-11-17 17:00 UTC
## Round ID:

N/A

## Testmerges:

N/A

## Reproduction:

Have the round begin, all shuttles will never move and get stuck like this:
https://imgur.com/a/TZexBcX

**Comment by Ghommie** [comment] 2019-11-17 18:27
That's caused by either #9825 or #9827 not being (test)merged.

**Closed as completed** 2019-11-17 18:32 UTC
