### ISSUE TITLE
clothes in the Historical Reanactor Crate have no sprites when weared

### ISSUE THREAD

**Issue by Fractious** [citadel-station/citadel-main#2041] opened 2017-07-17 03:05 UTC
I ordered the Historical Reanactor Crate via the supply console, called the shuttle and opened the box to see all the clothes inside it (they all have sprites). I tried to wear the clothes, but all of them had no sprites when equipped for some reasons like if my character was naked. 

Maybe they just never had one, but i'm still reporting it.

How to reproduce : Simply order a crate and try to equip all of the clothes and look at your character sprite.

**Comment by Poojawa** [comment] 2017-09-04 08:19
duplicate of #1982

**Closed as completed by Poojawa** 2017-09-04 08:19 UTC
